export const ERROR_CODES = [
  "VALIDATION_ERROR",
  "ADAPTER_UNSUPPORTED",
  "WORKFLOW_DIAGNOSTICS_ERROR",
  "REVISION_CONFLICT",
  "PERMISSION_DENIED",
  "INVALID_TRANSITION",
  "MISSING_ARTIFACT",
  "UNSAFE_PATH",
  "MISSING_EVIDENCE",
  "GATE_FAILED",
  "APPROVAL_REJECTED",
  "RUNTIME_UNAVAILABLE",
  "TERMINAL_UNAVAILABLE",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
